### ISSUE TITLE
Feature: Ping devices from dashboard

### ISSUE THREAD

**Issue by luckkmaxx** [herzhenr/simple-wake-on-lan#1]
Hi! Thanks for the app. It looks beautiful!
It doesnt need too much, just wake devices! but could be useful to see wich devices are running or not with a little red/green badge on each host in dashboard, wich indicates the ping result (online/offline).
I think the best way is to ping automatically while in dashboard, but would be also fine a manual control to only ping and not send magic packets

**Comment by herzhenr** [comment]
Hi, thank you for your positive feedback, I am glad you like the app!
This is a feature I have actually already planned to implement in the next couple of weeks. I want to ping the devices on the dashboard periodically in the background and show a small badge if they can be reached accordingly.
